# Generated by Django 5.2.7 on 2025-10-04 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('LINEAR_REGRESSION', 'Linear Regression'), ('ARIMA', 'ARIMA'), ('PROPHET', 'Prophet')], default='LINEAR_REGRESSION', max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('FAILED', 'Failed')], default='TRAINING', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('r2_score', models.FloatField(blank=True, help_text='R-squared score', null=True)),
                ('mse', models.FloatField(blank=True, help_text='Mean Squared Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('training_samples', models.IntegerField(default=0)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast Model',
                'verbose_name_plural': 'Forecast Models',
                'db_table': 'forecast_models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_lower', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_upper', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_demand', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.category')),
                ('forecast_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_forecasts', to='forecasting.forecastmodel')),
            ],
            options={
                'verbose_name': 'Category Forecast',
                'verbose_name_plural': 'Category Forecasts',
                'db_table': 'category_forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Date for which demand is predicted')),
                ('predicted_demand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_lower', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_upper', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_level', models.FloatField(default=95.0, help_text='Confidence level (e.g., 95%)')),
                ('actual_demand', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast_error', models.IntegerField(blank=True, null=True)),
                ('absolute_percentage_error', models.FloatField(blank=True, null=True)),
                ('is_peak_season', models.BooleanField(default=False)),
                ('seasonal_factor', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.forecastmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Forecast',
                'verbose_name_plural': 'Product Forecasts',
                'db_table': 'product_forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., Valentine's Day, Mother's Day", max_length=200)),
                ('season_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('MONTHLY', 'Monthly Pattern'), ('WEEKLY', 'Weekly Pattern'), ('SPECIAL', 'Special Event')], max_length=20)),
                ('start_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('end_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('end_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('demand_multiplier', models.FloatField(default=1.0, help_text='Expected demand increase (e.g., 2.5 = 250% of normal)')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='seasonal_patterns', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Seasonal Pattern',
                'verbose_name_plural': 'Seasonal Patterns',
                'db_table': 'seasonal_patterns',
                'ordering': ['start_month', 'start_day'],
            },
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('recommended_order_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(help_text='Why this recommendation was made')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('ORDERED', 'Ordered'), ('COMPLETED', 'Completed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('ordered_quantity', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_recommendations', to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='forecasting.productforecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_recommendations', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Recommendation',
                'verbose_name_plural': 'Stock Recommendations',
                'db_table': 'stock_recommendations',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.AddIndex(
            model_name='forecastmodel',
            index=models.Index(fields=['status', 'is_active'], name='forecast_mo_status_9c4ba5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryforecast',
            unique_together={('category', 'forecast_date', 'forecast_model')},
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['product', 'forecast_date'], name='product_for_product_4fd64d_idx'),
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['forecast_date'], name='product_for_forecas_2c30dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productforecast',
            unique_together={('product', 'forecast_date', 'forecast_model')},
        ),
        migrations.AddIndex(
            model_name='stockrecommendation',
            index=models.Index(fields=['status', 'priority'], name='stock_recom_status_b59f32_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecommendation',
            index=models.Index(fields=['product', 'status'], name='stock_recom_product_1adb9f_idx'),
        ),
    ]
