# Generated by Django 5.2.7 on 2025-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodel',
            name='model_type',
            field=models.CharField(choices=[('LINEAR_REGRESSION', 'Linear Regression')], default='LINEAR_REGRESSION', max_length=50),
        ),
    ]
